declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_API_URL: string;
    NEXT_PUBLIC_FIREBASE_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
    NEXT_PUBLIC_FIREBASE_APP_ID: string;
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: string;
    NEXT_PUBLIC_FIREBASE_IMAGE_BUCKET: string;
    NEXT_PUBLIC_FIREBASE_ATTESTATION_PROVIDER: string;
    NEXT_PUBLIC_ORACLE_CLOUD_SECRET_KEY: string;
    NEXT_PUBLIC_TENANCY_ID: string;
    NEXT_PUBLIC_USER_ID: string;
    NEXT_PUBLIC_ORACLE_IMAGE_BUCKET_PAR: string;
  }
}